spring:
    application:
        name: miniordermanagement

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

rabbitmq:
    order:
        exchange: order-exchange
        queue: order-queue
