spring:
    application:
        name: miniordermanagement

    datasource:
        url: jdbc:h2:file:./data/testdb
        driverClassName: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
            path: /h2-console

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

rabbitmq:
    order:
        exchange: order-exchange
        queue: order-queue
